FIELD_BENIGN_FILE = 'benign'
FIELD_MALIGN_FILE = 'malign'
FIELD_BENIGN_GRAPHS = 'benignGraphs'
FIELD_MALIGN_GRAPHS = 'malignGraphs'
FIELD_METHODS_ONLY_BY_MALIGN = 'methodsAccessedOnlyByMalign'
FIELD_METHODS = 'benignGraphContainsMalignGraph'
FIELD_HAS_DIFFERENT_TRACES = 'hasDifferentTraces'
FIELD_RANKING = 'ranking'
FIELD_APPS = 'apps'
FIELD_DISTANCES_BENIGN = 'distancesBenign'
FIELD_DISTANCES_MALIGN = 'distancesMalign'
FIELD_DISTANCES_ONLY_MALIGN = 'distancesOnlyMalign'

BENIGN_METHODS=1
MALIGN_METHODS=2
ONLY_MALIGN_METHODS=3