FIELD_BENIGN_FILE = 'benign'
FIELD_MALIGN_FILE = 'malign'
FIELD_BENIGN_GRAPHS = 'benignGraphs'
FIELD_MALIGN_GRAPHS = 'malignGraphs'
FIELD_METHODS_ONLY_BY_MALIGN = 'methodsAccessedOnlyByMalign'
FIELD_METHODS = 'benignGraphContainsMalignGraph'
FIELD_HAS_DIFFERENT_TRACES = 'hasDifferentTraces'
